name: "Release Update!"

on:
  push:
    branches:
      - "default"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: resource_pack
          dest: server-resources.zip
      - uses: ncipollo/release-action@v1.12.0
        with:
          owner: "KillerCamo"
          allowUpdates: "true"
          makeLatest: "true"
          name: "Default Resource Pack Update!"
          artifacts: "server-resources.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "Royals"

