name: "Release Update!"

on:
  push:
    branches:
      - "main"

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: "Server Resources Update!"
        artifacts: "release.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "2.0.2"
