name: "Release Update!"

on:
  push:
    branches:
      - "main"

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: ${{ github.workspace }}
          dest: ${{ github.workspace }}/server-resources.zip
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        owner: "KillerCamo"
        name: "Server Resources Update!"
        artifacts: "server-resources.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "2.0.${{ github.run_number }}"
