name: "Release Update!"

on:
  push:
    branches:
      - "main"

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: 'resource-pack'
        filename: 'server-resources.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: "Resource Pack Updated!"
        artifacts: "server-resources.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "2.0.${{ github.run_number }}"
