name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
     build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'server-resources.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
        steps:
        - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
